// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWLy_xWvxKQp-PCdo4vt9tCxQAKPzPuek',
    appId: '1:459891436782:web:a417b0fec0bc07c0b417ff',
    messagingSenderId: '459891436782',
    projectId: 'lifelog-3efdc',
    authDomain: 'lifelog-3efdc.firebaseapp.com',
    storageBucket: 'lifelog-3efdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1jLRQSPzEdUJS9xzqyTQpWQw3GXNdqzA',
    appId: '1:459891436782:android:fbd2c0d562071fefb417ff',
    messagingSenderId: '459891436782',
    projectId: 'lifelog-3efdc',
    storageBucket: 'lifelog-3efdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6kl5VAcMMnCi7RRU_r25xCo3-QE9Us0',
    appId: '1:459891436782:ios:b026dd794fcb7ec1b417ff',
    messagingSenderId: '459891436782',
    projectId: 'lifelog-3efdc',
    storageBucket: 'lifelog-3efdc.firebasestorage.app',
    iosBundleId: 'com.example.lifelog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj6kl5VAcMMnCi7RRU_r25xCo3-QE9Us0',
    appId: '1:459891436782:ios:b026dd794fcb7ec1b417ff',
    messagingSenderId: '459891436782',
    projectId: 'lifelog-3efdc',
    storageBucket: 'lifelog-3efdc.firebasestorage.app',
    iosBundleId: 'com.example.lifelog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWLy_xWvxKQp-PCdo4vt9tCxQAKPzPuek',
    appId: '1:459891436782:web:93007ec02a7d3bbdb417ff',
    messagingSenderId: '459891436782',
    projectId: 'lifelog-3efdc',
    authDomain: 'lifelog-3efdc.firebaseapp.com',
    storageBucket: 'lifelog-3efdc.firebasestorage.app',
  );

}